//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusLayerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Copy()
        {
            this.Histories = new HashSet<History>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public decimal CopyId { get; set; }
        public decimal BookId { get; set; }
        public string Location { get; set; }
        public Nullable<int> LocationInLibrary { get; set; }
        public Nullable<System.DateTime> DayOfBooking { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
        public string Status { get; set; }
        public string Id { get; set; }
        public Nullable<bool> isReserved { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
