//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusLayerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public decimal HistoryId { get; set; }
        public Nullable<decimal> CopyId { get; set; }
        public Nullable<System.DateTime> BookedDay { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Copy Copy { get; set; }
    }
}
