//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusLayerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public decimal RatingsId { get; set; }
        public decimal BookId { get; set; }
        public Nullable<double> sumofRatings { get; set; }
        public Nullable<int> numberofRatings { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
